### ISSUE TITLE
Bashslash for a delimiter doesn't work?

### ISSUE THREAD

**Issue by larrypl** [ColumPaget/ColumsCut#1]
```
Helios:ColumsCut larry$ echo one\\two\\three\\four | ccut -d \\ -f 4,1
one\two\three\four
Helios:ColumsCut larry$ echo one\\two\\three\\four | ccut -d '\' -f 4,1
one\two\three\four
```

I note, however, that this works:

```
Helios:ColumsCut larry$ echo one\\two\\three\\four | ccut -d '\\' -f 4,1
four\one
```

This is how GNU coreutils cut works:

```
Helios:ColumsCut larry$ echo 'one\two\three\four' | cut -d \\ -f 4,1
one\four
Helios:ColumsCut larry$ echo 'one\two\three\four' | cut -d '\' -f 4,1
one\four
Helios:ColumsCut larry$ echo 'one\two\three\four' | cut -d '\\' -f 4,1
gcut: the delimiter must be a single character
Try 'gcut --help' for more information.
```

**Comment by ColumPaget** [comment]
Backslashes?! Who would use backslashes? That's just evil.

I'll have a look at this tonight, thanks for reporting it.

**Comment by larrypl** [comment]
Yep, I'm evil! Don't know why I tried that, but it caused lots of odd results until I figured out it was the backslash that caused problems.

**Comment by ColumPaget** [comment]
I've looked into this, and it's an easy fix, but then you'd be unable to specify certain characters as a delimiter. Currently these quote sequences are recognized in the delimiter:

        \e                      escape
        \t                      tab
        \r                      carriage-return
        \n                      newline
        \xnn            where 'nn' is a two-digit hex-code

But recognizing '\\' would mean this doesn't work. I suppose I could add another command-line switch to turn on and off delimiter quoting. 

What do you think?

**Comment by ColumPaget** [comment]
In the end I decided to create a new '-e' option for quoted delimiter characters. '-e' seems a nice choice as 'echo' uses the same option, and its one up from '-d'. So now '-d' works as gnu cut.

Thanks for reporting this. I gave you a credit at the bottom of 'ccut --help'. I trust that's okay?

**Comment by larrypl** [comment]
Cool, thanks!
