### ISSUE TITLE
Should reverse field ranges work?

### ISSUE THREAD

**Issue by larrypl** [ColumPaget/ColumsCut#2]
E.g.,
`Helios:ColumsCut larry$ echo one,two,three,four | ccut -d , -f 4-1`
`four`

**Comment by ColumPaget** [comment]
Hmm, I never thought of that. Just pushed v2.8 in which these now work.

**Comment by larrypl** [comment]
Thanks! Does the fix make something like “8-4,1-2,9” work (i.e., mixed ranges, range directions, multiple ranges and single fields)?

Forgot to mention - off topic - I really like the quote support, and the variable (‘-V’) support seems potentially very useful.
