### ISSUE TITLE
Off-by-one error caused by backslash in delimstr?

### ISSUE THREAD

**Issue by larrypl** [ColumPaget/ColumsCut#3]
E.g., works as expected but with unprotected backslash:

`Helios:ColumsCut larry$ echo 'one\/two\/three\/four' | ccut -D '\/' -f 1,4`
`one\/four`
`Helios:ColumsCut larry$ echo 'one\/two\/three\/four' | ccut -D '\/' -f 1-4`
`one\/two\/three\/four`

Protected backslash truncates output:

`Helios:ColumsCut larry$ echo 'one\/two\/three\/four' | ccut -D '\\/' -f 1,4`
`one\/fou`
`Helios:ColumsCut larry$ echo 'one\/two\/three\/four' | ccut -D '\\/' -f 1-4`
`one\/two\/three\/fou`

**Comment by ColumPaget** [comment]
I think this will be the next issue I'll have a go at. It's an odd one this.

**Comment by ColumPaget** [comment]
I think this is fixed too now.

**Comment by ColumPaget** [comment]
Pretty sure this one is fixed, so I'm closing it.

**Comment by larrypl** [comment]
OK, looks good!
Two minor issues, illustrated in one command:
`larryp-mbp:ColumsCut larry$ echo -e 'one two three\noneXtwoXthreeX' | ./ccut -d X -f 10-1 | cat -nvet`
`     1  (null)(null)(null)(null)(null)(null)(null)(null)M-pone two three$`
`     2  XXXXXXXthreeXtwoM-pone$`
First - when there's no delimiter in a line of input, and the output requires additional (null) fields, it generates “(null)” rather than (what I'd expect) delimiters with nothing between them.
Second, it sometimes replaces the delimiter with a random character; a meta-p in the example above. It seems to always be the last delimiter in the line.
