### ISSUE TITLE
Should argument parsing ignore spacing?

### ISSUE THREAD

**Issue by larrypl** [ColumPaget/ColumsCut#4]
```
Helios:ColumsCut larry$ echo one,two,three,four | ccut -d, -f1
Helios:ColumsCut larry$ echo one,two,three,four | ccut -d, -f 1
ERROR: Failed to open [1]
Helios:ColumsCut larry$ echo one,two,three,four | ccut -d , -f1
ERROR: Argument missing after '-f1'
Helios:ColumsCut larry$ echo one,two,three,four | cut -d, -f1  
one
Helios:ColumsCut larry$ echo one,two,three,four | cut -d , -f1
one
Helios:ColumsCut larry$ echo one,two,three,four | cut -d, -f 1
one
```

**Comment by ColumPaget** [comment]
yeeesh, that's ugly. I think this might be a case where I'm happy to be different from gnu cut.

**Comment by larrypl** [comment]
Oh, well. Guess I'll have to train my hands to put spaces between flag and value!

**Comment by ColumPaget** [comment]
The exercise will do you good ;-)

**Comment by larrypl** [comment]
Ha!
Not to beat a dead horse, but most commands parse single letter flags with or without spaces (“ls -w100”, “sort -k1,2”, “ps -p1”, “cmp -i10”, etc.) but up to you.

**Comment by ColumPaget** [comment]
I know, I know, but part of the point of ccut is that it's pretty simple code, and this would really make it a lot more complex!

**Comment by larrypl** [comment]
No problem!
