### ISSUE TITLE
Feature Request: output array (and bug - extra blank line?)

### ISSUE THREAD

**Issue by larrypl** [ColumPaget/ColumsCut#5]
You're going to start disliking me :(

I numbered the output to make it more obvious:

```
1 Helios:~ larry$ echo -e 'one,"two a,two b",three,four\nfive,six,seven,eight' | ccut -d , -Q -f 2,3    
2 two a,two b,three
3 six,seven
4 Helios:~ larry$ echo -e 'one,"two a,two b",three,four\nfive,six,seven,eight' | ccut -d , -Q -f 2,3 -V a,b
5 a='two a,two b'; b='three'; 
6 
```
(Blank line generated for second line of output when variable generation is requested.)

By extention, it seems like it would be logical for variable generation to generate array definition statements for multiple rows; something like:

```
Helios:~ larry$ echo -e 'one,"two a,two b",three,four\nfive,six,seven,eight' | ccut -d , -Q -f 2,3 -V a,b
a[0]='two a,two b'; b[0]='three'; 
a[1]='six'; b[1]='seven'
```

**Comment by ColumPaget** [comment]
I think there's a bigger problem that 

        echo -e 'one,"two a,two b",three,four\nfive,six,seven,eight' | ccut -d , -Q -f 2,3    

should just print

        two a,two b,three

or am I missing something here?

**Comment by larrypl** [comment]
No, I think the way it currently works with respect to multiple lines of input is the way I'd expect it to work. If I only wanted the Nth line I'd pipe the output to head/tail/sed/awk/whatever.

**Comment by ColumPaget** [comment]
but isn't field 2 "two a two b" and field 3 "three,four\nfive"? Why does it output six and seven at all?

**Comment by larrypl** [comment]
Nope! This might make it clearer:
```
Helios:~ larry$ echo -e 'one,"two a,two b",three,four\nfive,six,seven,eight' | tee /dev/tty | ccut -d , -Q -f 2,3 
one,"two a,two b",three,four
five,six,seven,eight
two a,two b,three
six,seven
```

**Comment by ColumPaget** [comment]
Hi Larry,

Overlooked this report for two years! I still think it's working correctly. We are feeding it two lines:

one,"two a,two b",three,four
five,six,seven,eight

and asking it to clip out fields 2 and 3 of both, which would give:

two a,two b,three
six,seven

Which is exactly what it would produces, fields 2 and 3 of line 1 (two a,two b, three) and fields two and three of line two (six, seven)

Colum

**Comment by ColumPaget** [comment]
Oh, hang on, I can see I was saying that I thought it would behave differently to this. Now I think it's working correctly. Now I'm not sure what the original point here was?

**Comment by ColumPaget** [comment]
I think we fixed everything in this thread, so I'm closing it! Thanks again for the bug reports.
