### ISSUE TITLE
The -s / --only-delimited option seems to not work as expected

### ISSUE THREAD

**Issue by schragge** [ColumPaget/ColumsCut#9]
input: `seq -f '%.f to be output' 0 5 20|ccut -s -d 5 -f 2`
output:
```
 
to be output
<�V
 to be output
<�V
```

input: `seq -f '%.f to be output' 0 5 20|ccut --only-delimited -d 5 -f 2`
output:
```

 to be output
FU
 to be output
FU
```

input: `seq -f '%.f to be output' 0 5 20|ccut -d 5 -s -f 2`
output:
```

 to be output
2MU
 to be output
MU
```

input: `seq -f '%.f to be output' 0 5 20|ccut -d 5 -f 2 -s`
output:
```

 to be output
h�V
 to be output
h�V
```

Expected output in all cases is
```
 to be output
 to be output
```
I get the expected output with `cut` from GNU Coreutils:
`seq -f '%.f to be output' 0 5 20|cut -sd5 -f2`
or with `scut` from [Schily Tools](https://sourceforge.net/projects/schilytools):
`seq -f '%.f to be output' 0 5 20|scut d=5 f=2 -s`

OS: CentOS 8. I'm attaching the [Mock](https://github.com/rpm-software-management/mock/wiki) build log. My spec file is [here](https://app.box.com/s/jy3siq2jv91jiu2exw97vefbz3l3ysho).

[build.log](https://github.com/ColumPaget/ColumsCut/files/5538937/build.log)

**Comment by ColumPaget** [comment]
Thanks for this detailed bug report! Latest release (3.1) now fixes this issue.

Thanks again for reporting this.

**Comment by schragge** [comment]
Thank you. But you forgot to include the file `tests/multiline.txt` into distribution. From `check.sh` I infer it should be something like
```
1. this should be included*
2. this should not be included
3. this should be included*
```

**Comment by ColumPaget** [comment]
Darn, that's git for you. but how did it not error at travis-ci, I wonder?
